### PR TITLE
Error with OutsideEventPlugin that would lead to calling undefined function  

### PR DESCRIPTION
**Pull request by erzaehlsalex**
Hi, this is now the pull request we talked about. Please merge this. 
Cheers! :)

### CODE REVIEW

**Comment by shlomiassaf** [comment]
@erzaehlsalex Thanks!

I'm rebasing some of master's commits into it so other fixes will get in (mainly support for VEX4)

**Comment by erzaehlsalex** [comment]
Great! So afterwards you will publish version 3.0.2?
Thank you!

**Comment by shlomiassaf** [comment]
3.0.2 is the latest, I will publish 3.0.3

**Comment by shlomiassaf** [comment]
It will have a branch now
https://github.com/shlomiassaf/ngx-modialog/tree/3.x.x

**Comment by shlomiassaf** [comment]
ok, publish, hope it works smoothly :)

**Comment by erzaehlsalex** [comment]
Awesome! I will check it out tomorrow morning and shoot you a message, if everything works smoothly!

**Comment by erzaehlsalex** [comment]
Works perfect with Angular 4 :)

**Pull request merged**
